######################################################################
# Automatically generated by qmake (3.0) ?? ?? 16 16:23:55 2015
######################################################################

TEMPLATE = app
TARGET = IcenVision
INCLUDEPATH += .
QT += gui widgets
QT += network
# Input
HEADERS += showwidget.h
SOURCES += main.cpp showwidget.cpp
